### ISSUE TITLE
Clear method request

### ISSUE THREAD

**Issue by ZionPi** [martino2k6/StoreBox#15]
What if I want to clear all key-value pairs by using one single `clear` method?

**Comment by martino2k6** [comment]
Good call, I have somehow managed to miss this.

I'm thinking I could provide a `@ClearMethod` annotation for this. Alternatively I could also use the existing `@RemoveMethod` for the same purpose, but make it behave as clear-all if no `@KeyBy...` annotation or key argument has been specified, although this does not seem as clear cut as the first option.

**Comment by ZionPi** [comment]
`PreferenceManager.getDefaultSharedPreferences(context).edit()
        .clear().commit();` seems do the trick.But if **StoreBox**  can provide a way to specify the name of the sharepreference file  to avoid conflict with existed(shiped product) sharepreference file,that will be nice.
