### ISSUE TITLE
Remove?

### ISSUE THREAD

**Issue by westito** [martino2k6/StoreBox#8]
I can't remove values. Putting null causes exeption.

**Comment by martino2k6** [comment]
Thank you for the report. I'm somewhat dumbstruck that I managed to miss this, but it has been fixed in 1.0.1 which should be available in the repository now.

Please let me know if the new version fixes your issue and I will close the ticket.

**Comment by martino2k6** [comment]
Or you may also try 1.1.0 which has the bug fix for the crash as well as a newly added ```@RemoveMethod``` annotation. See the updated README file on how to use it.
