### ISSUE TITLE
add support for change listeners

### ISSUE THREAD

**Issue by martino2k6** [martino2k6/StoreBox#9]

**Comment by semanticer** [comment]
Take a look at https://github.com/pwittchen/prefser and his implementation v RxObservables on top of OnSharedPreferenceChangeListener

**Comment by martino2k6** [comment]
Thanks for the notice. I haven't looked at any other preference libraries when writing StoreBox as it was a project lying somewhere between satisfying my own curiosity and approaching a problem I've come across before.

What you linked does look quite nice though. When I get around to working on this, which will definitely have to happen after #3, I will most likely do a basic implementation first without Rx support and then add it later. I have a rough idea of how I could piggy-back on top of OnSharedPreferenceChangeListener using annotations, but Rx is something that would require more thought.

**Comment by martino2k6** [comment]
22e7d5d17bddde21bbcc9322605f8e9aa4425975 still requires docs, cleaning up when an OnValueChangedListener is no longer strongly referenced outside of the library's class instances, and perhaps support for (un)registering multiple listeners through varargs.

**Comment by martino2k6** [comment]
Implementation without Rx support completed at 85264507b84642e3aa0fd277ce5619e13295f02e.
